name: Docker Build

on:
  push:
    branches:
    - master

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'e621ng'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Generate Docker tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/e621ng/autocompleted
          tags: |
            type=sha,format=long,prefix=
          flavor: |
            latest=true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
